### ISSUE TITLE
sx1262

### ISSUE THREAD

**Issue by tarundholariya** [Lora-net/sx126x_driver#1]
hello please provided main.c for sx126x_driver any one help me how to send data to gatway

**Comment by matthieuantoine** [comment]
Hello, Examples of implementation will be published soon.

**Comment by piyushy6** [comment]
> Hello, Examples of implementation will be published soon.
Hi,
When will you publish?

**Comment by ShiauweiZhao** [comment]
> Hello, Examples of implementation will be published soon.

When will you publish?

**Comment by lunaleevip** [comment]
> Hello, Examples of implementation will be published soon.

When will you publish?

**Comment by UncleGrumpy** [comment]
It's been a year and a half. Are those examples ever coming?  How about just a little bit of documentation?

**Comment by mx-cyber** [comment]
I hope the example will be released as soon as possible

**Comment by jeanguerin** [comment]
Hello, 
This driver is promising but unfortunately lack of examples or documentation makes it hard to implement. Please help us...

**Comment by matthieuantoine** [comment]
Hello.

You can find an implementation example of the driver HAL in the minimal example available https://github.com/Lora-net/SWL2001 (see https://github.com/Lora-net/SWL2001/blob/master/utilities/user_app/radio_hal/sx126x_hal.c).

A SDK for SX126x transceivers is under development and currently being finalized. I do not have official ETA unfortunately.

**Comment by ABHITHLALC** [comment]
Has the sx126x driver been implemented by anyone? Could someone assist me in locating an example or any documentation on using this driver? Your help would be greatly appreciated

**Comment by gbartnik** [comment]
Hello,

The SX126x driver was updated in December 2023. It can be found in this repository: https://github.com/Lora-net/sx126x_driver/ 

Usage examples can be found in the Trnasceiver SDK - also updated last month, found here: https://github.com/Lora-net/SWSD003/ 

Hope this helps,

Grant
