### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by evandavey** [Lora-net/sx126x_driver#3]
- What is the status of the driver?

- Will this become the reference implementation (providing a HAL interface for porting) as there are currently multiple drivers (official and unofficial):
   - https://github.com/Lora-net/LoRaMac-node/tree/master/src/radio/sx126x
   - https://github.com/ARMmbed/mbed-os/tree/master/connectivity/drivers/lora/COMPONENT_SX126X
   - https://os.mbed.com/teams/Semtech/code/SX126xLib
   - https://github.com/beegee-tokyo/SX126x-Arduino
   - https://github.com/tinytronix/SX126x

**Comment by matthieuantoine** [comment]
This driver is still alive (a new release is expected in the coming weeks) and is now the reference implementation from Semtech for SX126x family.

What do you mean by `providing a HAL interface for porting`? The hardware-related functions that the user has to implement are all located in `sx126x_hal.h`. Is there something else you would like to see added?

**Comment by evandavey** [comment]
That's good news, thanks.

Yes, I like your HAL structure.  I meant, that I hope that other frameworks e.g. MBED/I-Cube adapt this style. The MBED driver has no good HAL abstraction within the driver and therefore the library becomes very out-of-date versus the reference library. See e.g. https://github.com/ARMmbed/mbed-os-example-lorawan/issues/227 where we are having achieving deep sleep as the MBED driver makes no allowance for gpio init and deinit on wakeup/sleep.  And https://github.com/ARMmbed/mbed-os-example-lorawan/issues/222#issuecomment-886004432 where the SX1276 driver doesn't disable TCXO.  Looks like a big chunk of work however to de-segregate given how opinionated MBED is with respect to the driver interface with the stack.

**Comment by evandavey** [comment]
@matthieuantoine - is a new release still expected?

**Comment by matthieuantoine** [comment]
Hello @evandavey - a new version of the driver is available.
