### ISSUE TITLE
Error in library sx126x.c

### ISSUE THREAD

**Issue by StressTest** [Lora-net/sx126x_driver#4]
In the library (sx126x.c), the command length is 3. In the [documentation](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000HT76/7Nka9W5WgugoZe.xwIHJy6ebj1hW8UJ.USO_Pt2CLLo) ( page 84) , the command length is 2 (highlighted in red). Response (data) 1 byte long (highlighted in blue)

    SX126X_SIZE_GET_PKT_TYPE               = 3,

![image](https://user-images.githubusercontent.com/23332012/143852494-80659254-bad2-4091-9f0a-2188a8609791.png)

**Comment by matthieuantoine** [comment]
Hello @StressTest - thanks for reporting this issue!

The fix is already applied in our internal development environment. A new version of the driver will be released before end of  this year.

**Comment by matthieuantoine** [comment]
Hello @StressTest - this is now fixed in the version 2.0.1.
