### ISSUE TITLE
FHSS only used in GMSK ?

### ISSUE THREAD

**Issue by qq963598371** [Lora-net/sx126x_driver#7]
this enum only has one . So maybe this code only used in GMSK?
typedef enum lr_fhss_v1_modulation_type_e
{
    LR_FHSS_V1_MODULATION_TYPE_GMSK_488 = 0,
} lr_fhss_v1_modulation_type_t;

**Comment by matthieuantoine** [comment]
This this the only possible parameter when doing LR-FHSS.
