### ISSUE TITLE
Range check of sx126x_set_rx_duty_cycle

### ISSUE THREAD

**Issue by ghost** [Lora-net/sx126x_driver#9]
May I suggest a range check in the function
 
`sx126x_status_t sx126x_set_rx_duty_cycle( const void* context, const uint32_t rx_time_in_ms,
                                          const uint32_t sleep_time_in_ms )`

The sx126x only provides 24 bits for setting the on and off times for rx duty cycle.

Either check for over maximum and set maximum or return an error.

`sx126x_status_t sx126x_set_rx_duty_cycle( const void* context, const uint32_t rx_time_in_ms,
                                          const uint32_t sleep_time_in_ms )
{
    const uint32_t rx_time_in_rtc_step    = sx126x_convert_timeout_in_ms_to_rtc_step( rx_time_in_ms );
    const uint32_t sleep_time_in_rtc_step = sx126x_convert_timeout_in_ms_to_rtc_step( sleep_time_in_ms );

    if (rx_time_in_rtc_step >= (1 << 24))
    {
        rx_time_in_rtc_step = (1 << 24) - 1;
    }

    if (sleep_time_in_rtc_step >= (1 << 24))
    {
        sleep_time_in_rtc_step = (1 << 24) - 1;
    }

    return sx126x_set_rx_duty_cycle_with_timings_in_rtc_step( context, rx_time_in_rtc_step, sleep_time_in_rtc_step );
}`

**Comment by opeyrard** [comment]
Thank you very much for your proposal of improvement.
We do not plan to have this check in the driver.
